name: CI/CD

on:
  push:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    env:
      DATABASE_URL_TEST: ${{ secrets.DATABASE_URL_TEST }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
      BASE_PUBLIC_URL: ${{ secrets.BASE_PUBLIC_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
      - name: Check running test is passed or failed
        run: |
          echo "Running tests..."
          # Insert your test commands here
          command_exit_code=$?
          echo "Command exited with status code $command_exit_code"
          if [ $? -eq 0 ]
          then
            echo "Tests passed!"
          else
            echo "Tests failed!"
            exit 1
          fi
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VARCEL_SECRET_KEY }}
          vercel-org-id: ${{ secrets.VARCEL_USER_ID}} #Required
          vercel-project-id: ${{ secrets.VARCEL_PROJECT_ID}} #Required
