name: CI/CD

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build --if-present
  test:
    needs: build
    env:
      DATABASE_URL_TEST: ${{ secrets.DATABASE_URL_TEST }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
      BASE_PUBLIC_URL: ${{ secrets.BASE_PUBLIC_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
